//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tín_Phát_Metech.EF.Data.edmx.Data.tt
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTP
    {
        public string Ma_BTP { get; set; }
        public string Ten_BTP { get; set; }
        public string DVT_BTP { get; set; }
        public Nullable<short> SLMin_BTP { get; set; }
        public string Ma_Kho { get; set; }
        public Nullable<byte> TKCP_BTP { get; set; }
        public Nullable<decimal> Gia_BTP { get; set; }
        public string Note_BTP { get; set; }
        public byte[] Image_BTP { get; set; }
    }
}
