//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Tín_Phát_Metech.EF.Data.edmx.Data.tt;

namespace Tín_Phát_Metech.EF.Data.edmx.Data.Context.tt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TinPhatEntities : DbContext
    {
        public TinPhatEntities()
            : base("name=TinPhatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KH> KH { get; set; }
        public virtual DbSet<NCC> NCC { get; set; }
        public virtual DbSet<NV> NV { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<To> To { get; set; }
        public virtual DbSet<Chucvu> Chucvu { get; set; }
        public virtual DbSet<BTP> BTP { get; set; }
        public virtual DbSet<DongiaSP> DongiaSP { get; set; }
        public virtual DbSet<DVCD> DVCD { get; set; }
        public virtual DbSet<MaQC> MaQC { get; set; }
        public virtual DbSet<NVL> NVL { get; set; }
        public virtual DbSet<THSP> THSP { get; set; }
        public virtual DbSet<TP> TP { get; set; }
    }
}
