//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tín_Phát_Metech.EF.Data.edmx.Data.tt
{
    using System;
    using System.Collections.Generic;
    
    public partial class DongiaSP
    {
        public string Ma_DG { get; set; }
        public string Ma_SP { get; set; }
        public string Ten_SP { get; set; }
        public string DVT { get; set; }
        public short SL { get; set; }
        public short Gia { get; set; }
        public string Note { get; set; }
    }
}
