//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tín_Phát_Metech.EF.Data.edmx.Data.tt
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH
    {
        public string Ma_KH { get; set; }
        public string Ten_KH { get; set; }
        public string Diachi_KH { get; set; }
        public string Note_KH { get; set; }
        public bool Is_NCC { get; set; }
    }
}
