//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tín_Phát_Metech.EF.Data.edmx.Data.tt
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaQC
    {
        public string Ma_QC { get; set; }
        public string Ten_QC { get; set; }
        public bool Trung_QC { get; set; }
        public bool Theodoi_QC { get; set; }
    }
}
