//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tín_Phát_Metech.EF.Data.edmx.Data.tt
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV
    {
        public string Ma_NV { get; set; }
        public byte[] Image_NV { get; set; }
        public string Ma_To { get; set; }
        public string Ma_User { get; set; }
        public string Ten_NV { get; set; }
        public bool Gioitinh_NV { get; set; }
        public string Diachi_NV { get; set; }
        public Nullable<int> SDT_NV { get; set; }
        public Nullable<int> CMT_NV { get; set; }
        public System.DateTime Creat_Date { get; set; }
        public System.DateTime By_Date { get; set; }
    }
}
