//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tín_Phát_Metech.EF.Data.edmx.Data.tt
{
    using System;
    using System.Collections.Generic;
    
    public partial class NVL
    {
        public string Ma_NL { get; set; }
        public string Ten_NL { get; set; }
        public string DVT_NL { get; set; }
        public Nullable<short> SLMin_NL { get; set; }
        public string Ma_Kho { get; set; }
        public Nullable<byte> TKCP_NL { get; set; }
        public Nullable<decimal> Gia_NL { get; set; }
        public string Note_NL { get; set; }
        public byte[] Image_NL { get; set; }
    }
}
