//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tín_Phát_Metech.EF.Data.edmx.Data.tt
{
    using System;
    using System.Collections.Generic;
    
    public partial class THSP
    {
        public byte Date_THSP { get; set; }
        public decimal Ma_THSP { get; set; }
        public string Ma_Kho { get; set; }
        public string TenSP { get; set; }
        public string DVT { get; set; }
        public short SL { get; set; }
        public short Gia { get; set; }
        public decimal Tien { get; set; }
        public string Ma_NV { get; set; }
        public string Note { get; set; }
    }
}
