//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tín_Phát_Metech.EF.Data.edmx.Data.tt
{
    using System;
    using System.Collections.Generic;
    
    public partial class TP
    {
        public string Ma_TP { get; set; }
        public string Ten_TP { get; set; }
        public string DVT_TP { get; set; }
        public string Ma_Kho { get; set; }
        public Nullable<byte> TKDT_TP { get; set; }
        public Nullable<decimal> Gia_TP { get; set; }
        public string Note_TP { get; set; }
        public byte[] Image_TP { get; set; }
    }
}
