//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tín_Phát_Metech.EF.Data.edmx.Data.tt
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Ma_User { get; set; }
        public string Ma_NV { get; set; }
        public string User1 { get; set; }
        public string Pass { get; set; }
        public string Permision { get; set; }
        public System.DateTime Creat_Date { get; set; }
        public System.DateTime By_Date { get; set; }
    }
}
